### ISSUE TITLE
cannot run the example code..

### ISSUE THREAD

**Issue by rcdosado** [DataTeaser/textteaser#2]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "textteaser\__init__.py", line 11, in summarize
    result = self.summarizer.summarize(text, title, source, category)
  File "textteaser\summarizer.py", line 11, in summarize
    sentences = self.parser.splitSentences(text)
  File "textteaser\parser.py", line 61, in splitSentences
    tokenizer = nltk.data.load('file:' + os.path.dirname(os.path.abspath(__file
_)) + '/trainer/english.pickle')
  File "c:\Python27\lib\site-packages\nltk\data.py", line 786, in load
    resource_val = pickle.load(opened_resource)
ImportError: No module named copy_reg
```

then

```
C:\Users\user>pip install copy_reg
Downloading/unpacking copy-reg
  Could not find any downloads that satisfy the requirement copy-reg
Cleaning up...
No distributions at all found for copy-reg
Storing debug log for failure in C:\Users\user\pip\pip.log
```

**Comment by MojoJolo** [comment]
Hi @rcdosado. I'm not familiar with the bug but I found this: http://stackoverflow.com/questions/556269/importerror-no-module-named-copy-reg-pickle

**Comment by rcdosado** [comment]
i have run this in win7 btw, seems like compatibility issue?...thanks anyway sir..

**Comment by MojoJolo** [comment]
Looks like it. Will close this issue.
