### ISSUE TITLE
ImportError: No module named copy_reg

### ISSUE THREAD

**Issue by valentinedwv** [DataTeaser/textteaser#3]
Issues with pickle?
Windows 10 python 2.7.6, 

C:\Users\valentin\textteaser_nltk\Scripts\python.exe D:/dev_earthcube/textteaser/test.py
Traceback (most recent call last):
  File "D:/dev_earthcube/textteaser/test.py", line 12, in <module>
    sentences = tt.summarize(title, text)
  File "D:\dev_earthcube\textteaser\textteaser\__init__.py", line 13, in summarize
    result = self.summarizer.summarize(text, title, source, category)
  File "D:\dev_earthcube\textteaser\textteaser\summarizer.py", line 11, in summarize
    sentences = self.parser.splitSentences(text)
  File "D:\dev_earthcube\textteaser\textteaser\parser.py", line 61, in splitSentences
    tokenizer = nltk.data.load('file:' + os.path.dirname(os.path.abspath(__file__)) + '/trainer/english.pickle')
  File "C:\Users\valentin\textteaser_nltk\lib\site-packages\nltk\data.py", line 786, in load
    resource_val = pickle.load(opened_resource)
ImportError: No module named copy_reg

**Comment by MojoJolo** [comment]
Looks like an issue with pickle and Windows.
http://stackoverflow.com/questions/556269/importerror-no-module-named-copy-reg-pickle

**Comment by pavelmalai** [comment]
I've been struggling with the same problem, and I found that the problem is, git is messing with EOF. After I downloaded it as zip, it compiled just fine.

**Comment by maronin** [comment]
@pavelmalai This fixed the issue for me. Thanks!

**Comment by graichen** [comment]
See https://stackoverflow.com/questions/556269/importerror-no-module-named-copy-reg-pickle and consider saving as binary instead of text when you open the file.

**Comment by Ayla93** [comment]
Hi maronin and pavelmalai. may i know what did you guys download as a zip file? Im struggling with the same errors

**Comment by pavelmalai** [comment]
@Ayla93 Just download the project by using the Download Zip button, and not by cloning it.
